server:
  port: 8890

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soccer-bill-splitter
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update